services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: ua_history_assistant
    depends_on:
      - qdrant
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333