services:
  app:
    build: .
    container_name: ua_history_assistant
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./models:app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]