name: UA_history_assistant_RAG
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - ipykernel
  - pyarrow
  - sqlite
  - requests
  - tqdm
  - regex
  - pyyaml
  - pillow
  - pip:
      - langchain
      - langchain-core
      - langchain-google-genai
      - langchain-qdrant
      - langgraph
      - langsmith
      - transformers
      - datasets
      - sentence-transformers
      - qdrant-client
      - accelerate
      - bitsandbytes
      - peft
      - safetensors
      - huggingface-hub
      - pymupdf
      - beautifulsoup4
      - lxml
      - orjson
      - zstandard