from src.config import settings

PROJECT_PATH = settings.PROJECT_ROOT
DATA_PATH = settings.DATA_DIR

DFS_PATH = settings.DFS_PATH
TEXTBOOKS_DF_PATH = settings.TEXTBOOKS_DF_PATH
IMAGES_DF_PATH = settings.IMAGES_DF_PATH
TEXT_BLOCKS_DF_PATH = settings.TEXT_BLOCKS_DF_PATH
CHUNKS_DF_PATH = settings.CHUNKS_DF_PATH
MODELS_DIR_PATH = settings.MODELS_DIR_PATH

TEXTBOOKS_DIR_PATH = settings.TEXTBOOKS_DIR_PATH

IMAGES_DIR_PATH = settings.IMAGES_DIR_PATH
REJECTED_IMAGES_DIR_PATH = settings.REJECTED_IMAGES_DIR_PATH

PROMPTS_DIR_PATH = settings.PROMPTS_DIR_PATH